# Automatically generated file. DO NOT MODIFY
#
# This file is generated by     vendor/xiaomi/umi-miuicamera/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/xiaomi/umi-miuicamera/common

PRODUCT_COPY_FILES += \
    vendor/xiaomi/umi-miuicamera/common/proprietary/system/lib64/android.hardware.camera.common@1.0.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/android.hardware.camera.common@1.0.so \
    vendor/xiaomi/umi-miuicamera/common/proprietary/system/lib64/libDocumentProcess.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libDocumentProcess.so \
    vendor/xiaomi/umi-miuicamera/common/proprietary/system/lib64/libcom.xiaomi.camera.mianodejni.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libcom.xiaomi.camera.mianodejni.so \
    vendor/xiaomi/umi-miuicamera/common/proprietary/system/lib64/libcom.xiaomi.camera.requestutil.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libcom.xiaomi.camera.requestutil.so \
    vendor/xiaomi/umi-miuicamera/common/proprietary/system/lib64/libfenshen_snpe.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libfenshen_snpe.so \
    vendor/xiaomi/umi-miuicamera/common/proprietary/system/lib64/libffmpeg.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libffmpeg.so \
    vendor/xiaomi/umi-miuicamera/common/proprietary/system/lib64/libhidltransport.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libhidltransport.so \
    vendor/xiaomi/umi-miuicamera/common/proprietary/system/lib64/libjni_jpegutil_xiaomi.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libjni_jpegutil_xiaomi.so \
    vendor/xiaomi/umi-miuicamera/common/proprietary/system/lib64/libmimoji_avatarengine.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libmimoji_avatarengine.so \
    vendor/xiaomi/umi-miuicamera/common/proprietary/system/lib64/libmimoji_bokeh_845_video.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libmimoji_bokeh_845_video.so \
    vendor/xiaomi/umi-miuicamera/common/proprietary/system/lib64/libmimoji_jni.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libmimoji_jni.so \
    vendor/xiaomi/umi-miuicamera/common/proprietary/system/lib64/libmimoji_soundsupport.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libmimoji_soundsupport.so \
    vendor/xiaomi/umi-miuicamera/common/proprietary/system/lib64/libmimoji_tracking.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libmimoji_tracking.so \
    vendor/xiaomi/umi-miuicamera/common/proprietary/system/lib64/libmimoji_video2gif.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libmimoji_video2gif.so \
    vendor/xiaomi/umi-miuicamera/common/proprietary/system/lib64/libmotion_photo.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libmotion_photo.so \
    vendor/xiaomi/umi-miuicamera/common/proprietary/system/lib64/libmotion_photo_mace.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libmotion_photo_mace.so \
    vendor/xiaomi/umi-miuicamera/common/proprietary/system/lib64/libmulti-wakeup-engine.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libmulti-wakeup-engine.so \
    vendor/xiaomi/umi-miuicamera/common/proprietary/system/lib64/librecord_video.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/librecord_video.so \
    vendor/xiaomi/umi-miuicamera/common/proprietary/system/lib64/vendor.xiaomi.hardware.campostproc@1.0.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vendor.xiaomi.hardware.campostproc@1.0.so \
    vendor/xiaomi/umi-miuicamera/common/proprietary/system/priv-app/MiuiCamera/lib/arm64/libcamera_algoup_jni.xiaomi.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/MiuiCamera/lib/arm64/libcamera_algoup_jni.xiaomi.so \
    vendor/xiaomi/umi-miuicamera/common/proprietary/system/priv-app/MiuiCamera/lib/arm64/libcamera_mianode_jni.xiaomi.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/MiuiCamera/lib/arm64/libcamera_mianode_jni.xiaomi.so \
    vendor/xiaomi/umi-miuicamera/common/proprietary/vendor/lib64/libalCFR.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libalCFR.so \
    vendor/xiaomi/umi-miuicamera/common/proprietary/vendor/lib64/libarcmulticamsat.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libarcmulticamsat.so \
    vendor/xiaomi/umi-miuicamera/common/proprietary/vendor/lib64/libarcsat.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libarcsat.so \
    vendor/xiaomi/umi-miuicamera/common/proprietary/vendor/lib64/libflaw.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libflaw.so \
    vendor/xiaomi/umi-miuicamera/common/proprietary/vendor/lib64/libmiai_deblur.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libmiai_deblur.so \
    vendor/xiaomi/umi-miuicamera/common/proprietary/vendor/lib64/libmulticam_optical_zoom_control.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libmulticam_optical_zoom_control.so \
    vendor/xiaomi/umi-miuicamera/common/proprietary/vendor/lib64/libsupermoon.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libsupermoon.so \
    vendor/xiaomi/umi-miuicamera/common/proprietary/vendor/lib64/libdl.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libdl.so \
    vendor/xiaomi/umi-miuicamera/common/proprietary/vendor/lib64/libEGL.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libEGL.so \
    vendor/xiaomi/umi-miuicamera/common/proprietary/vendor/lib64/libGLESv2.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libGLESv2.so \
    vendor/xiaomi/umi-miuicamera/common/proprietary/vendor/lib64/libHalSuperSensorServer.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libHalSuperSensorServer.so \
    vendor/xiaomi/umi-miuicamera/common/proprietary/vendor/lib64/libion.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libion.so \
    vendor/xiaomi/umi-miuicamera/common/proprietary/vendor/lib64/liblog.so:$(TARGET_COPY_OUT_VENDOR)/lib64/liblog.so \
    vendor/xiaomi/umi-miuicamera/common/proprietary/vendor/lib64/libm.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libm.so \
    vendor/xiaomi/umi-miuicamera/common/proprietary/vendor/lib64/libmialgo_ie_capture.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libmialgo_ie_capture.so \
    vendor/xiaomi/umi-miuicamera/common/proprietary/vendor/lib64/libmialgoengine.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libmialgoengine.so \
    vendor/xiaomi/umi-miuicamera/common/proprietary/vendor/lib64/libnativewindow.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libnativewindow.so \
    vendor/xiaomi/umi-miuicamera/common/proprietary/vendor/lib64/librelight_only.so:$(TARGET_COPY_OUT_VENDOR)/lib64/librelight_only.so \
    vendor/xiaomi/umi-miuicamera/common/proprietary/vendor/lib64/libSuperSensorCPU.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libSuperSensorCPU.so \
    vendor/xiaomi/umi-miuicamera/common/proprietary/vendor/lib64/libSuperSensor.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libSuperSensor.so

PRODUCT_PACKAGES += \
    MiuiCamera

